apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  DB_USER: airflow
  DB_PASS: airflow
  DB_HOST: host.minikube.internal # важно для Minikube!
  DB_NAME: airflow
